# app/schemas.py
from typing import Optional
from sqlmodel import SQLModel

# We can reuse the fields from our database model by inheriting from it.
from app.models import Workflow

# Schema for creating a workflow (what the user sends to the API)
# It doesn't include the 'id' because that's generated by the database.
class WorkflowCreate(SQLModel):
    name: str
    description: Optional[str] = None

# Schema for reading a workflow (what the API sends back to the user)
# It includes the 'id'.
class WorkflowRead(SQLModel):
    id: int
    name: str
    description: Optional[str] = None